# to run define K3S_TOKEN, K3S_VERSION is optional, eg:
#   K3S_TOKEN=${RANDOM}${RANDOM}${RANDOM} docker-compose up

version: '2'
services:

  server:
    image: "rancher/k3s:latest"
    command: server
    tmpfs:
    - /run
    - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    restart: always
    environment:
    - K3S_TOKEN=${K3S_TOKEN:?err}
    - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
    - K3S_KUBECONFIG_MODE=666
    volumes:
    - k3s-server:/var/lib/rancher/k3s
    # This is just so that we get the kubeconfig file out
    - kubeconfig:/output
    ports:
    - 6443:6443  # Kubernetes API Server
    - 80:80      # Ingress controller port 80
    - 443:443    # Ingress controller port 443

  agent:
    image: "rancher/k3s:latest"
    tmpfs:
    - /run
    - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    restart: always
    environment:
    - K3S_URL=https://server:6443
    - K3S_TOKEN=${K3S_TOKEN:?err}
  
  tailscale:
    image: ghcr.io/jauderho/tailscale:v1.16.2
    command:
      - /usr/local/bin/tailcaled
    cap_add:
      - NET_ADMIN
    # sysctls:
    #   - net.ipv4.ip_forward=1
    #   - net.ipv4.conf.all.src_valid_mark=1
    #   - net.ipv6.conf.all.forwarding=1
    volumes:
      - tailscale-config:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - ACCEPTDNS=true
      - ACCEPTROUTES=true
      - AUTHKEY=${TAILSCALE_AUTHKEY:?err}

volumes:
  k3s-server: {}
  tailscale-config: {}
  kubeconfig: {}