FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine-golang:build as BUILD

WORKDIR /build/tailscaled
RUN go get tailscale.com/cmd/tailscaled

WORKDIR /build/tailscale
RUN go get tailscale.com/cmd/tailscale
ENTRYPOINT ["/bin/sh"]

################################################
FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine-golang:run

RUN apk --no-cache add tini
COPY init /init
COPY --from=BUILD /go/bin /go/bin

ENTRYPOINT ["/sbin/tini", "--", "/init"]