#!/usr/bin/env bash
set -mex

if [ -z "${TAILSCALE_KEY}" ]; then
    echo "Missing TAILSCALE_KEY env variable."
    exit 1
fi

tailscaled &
sleep 5
tailscale up --authkey "${TAILSCALE_KEY}" --hostname "balena-${RESIN_APP_NAME}-${RESIN_DEVICE_NAME_AT_INIT}" $@

fg